package game.dragonhero.mapping.main;

// Generated Jan 9, 2013 3:15:13 PM by Hibernate Tools 3.4.0.CR1

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * User generated by hbm2java
 */
@Entity
@Data
public class ConfigLanguage implements java.io.Serializable {

    @Id
    private String k;
    private String vi;
    private String en, km, jp, ru, zh;

    public ConfigLanguage() {
    }
}
